web/fastline/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('taobaoside.urls')),
    path('admin/', admin.site.urls),
]

web/taobaoside/urls.py
from django.urls import path

from . import views
app_name = 'taobaoside'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('search-result',views.ProductSearch.as_view(),name='search_item'),
    path('search-result/<slug:slug>/detail',views.ItemDetails.as_view(),name='item_detail'),
    path('search-result/<slug:slug>/add-shopee',views.AddShopee.as_view(),name='add_shopee'),
    path('product-added',views.AddShopee.as_view(),name='product_added')
]

web/taobaoside/models.py
from django.db import models

# Create your models here.

web/taobaoside/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from taobaoside.taobao_api import *

# Create your views here.
class Home(generic.ListView):
    #get -> http with a box
    def get(self,request, *args, **kwargs):
        return render(request, 'taobaoside/home.html')



class ProductSearch(generic.ListView):
    #load product page
    def post(self,request, *args, **kwargs):
        search_query = request.POST['search_query']
        print(search_query)

        #function to search the key word with taobao api
        items_found = taobao_search(search_query,0)
        #print(items_found)
        context = {'items':items_found}
        #Load the data into a dict
        return render(request, 'taobaoside/product_search_result.html',context=context)


class ItemDetails(generic.ListView):
    #load product detail
    # With an add shoppee button
    def get(self,request, *args, **kwargs):
        #print(kwargs)
        item_id = kwargs['slug']
        context = taobao_item_search(item_id)
        print('ok')
        print(context)
        print('ok')
        #print(context['images'][0])
        return render(request, 'taobaoside/item_details.html',context=context)


class AddShopee(generic.ListView):

    def get(self,request, *args, **kwargs):
        item_id = kwargs['slug']
        context = taobao_item_search(item_id)
        return render(request, 'taobaoside/add_item.html',context=context)

    def post(self,request, *args, **kwargs):
        # Add to shopee
        return render(request, 'taobaoside/product_added.html')






# average_BMI = 0
# name_list = list(d.keys())
# for key in name_list:
#     height = d[key]['h']
#     weight = d[key]['w']
#     BMI = w/(h/100)**2
#     average_BMI += BMI
#
# average_BMI = average_BMI /len(d)

web/taobaoside/templates/taobaoside/add_item.html
<html>
  <head>
    <title>Product</title>
    <style>
      .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #4CAF50;
        color: white;
        text-decoration: none;
        border-radius: 4px;
      }
    </style>
    <style>
  /* Hide the tooltip text by default */
  .tooltiptext {
    display: none;
  }

  /* Show the tooltip text when the user hovers over the "?" symbol */
  .tooltip:hover .tooltiptext {
    display: inline-block;
  }
</style>

  </head>
  <body>
    <h1>Product details</h1>
    <div style="display: flex;">
      <div style="width: 200px;">
        <img src="{{ details.images.0 }}" alt="{{ details.title }}" style="width: 200px;" />
      </div>
      <div>
        <form action="{%url 'taobaoside:product_added'%}" method="POST">
          {% csrf_token %}
          <label for="name">Title:</label>
          <input type="text" id="name" name="name" value="{{ details.title }}"style="width:300px" />
          <br />
          <label for="price">Your selling Price:</label>
          <input type="number" id="price" name="price" value="{{ details.promotion_price }}" onchange="updatePrice()"/>


          <select id="currency" name="currency" onchange="updatePrice()">
            <option value="CNY">CNY</option>
            <option value="TWD">TWD</option>
          </select>

        <p>Profit : </p>
        <p id="profit-display">0</p>
        <label for="description">Add a product description : </label>
        <br />
        <textarea name="description" id="description" cols="30" rows="10"></textarea>
        <br />
        <label for="autopurchase">
       Activate Autopurchase:
       <input type="checkbox" name="autopurchase" id="autopurchase">
       <span class="tooltip">?
         <span class="tooltiptext">
           Enabling this option will automatically purchase the product when a customer buys it.
         </span>
       </span>
     </label><br><br>
        <button type="submit">Add to Shopee</button>
        </form>
      </div>

    </div>
    <div>
      <h3>Additional Images</h3>
      <div style="width: 1200px;">
        {% for image in details.images|slice:"1:" %}
          <img src="{{ image }}" alt="{{ details.title }} additional image" style="width:200px"/>
        {% endfor %}
      </div>

      <div style="width: 1200px;">

        {% for image in images %}
          <img src="{{ image }}" alt="{{ details.title }} additional image" style="width:300px"/>
        {% endfor %}
      </div>
    </div>
  </body>

  <script>
function updatePrice() {
    // Get the selected currency
    var currency = document.querySelector('[name="currency"]').value;

    var bought_price = {{ details.promotion_price }}

    // Get the current price
    var price = parseFloat(document.querySelector('[name="price"]').value);

    // Convert the price to the selected currency
    if (currency == 'CNY') {
        // Convert to CNY
        profit = price - bought_price;
        var symbol = '¥';
    } else if (currency == 'TWD') {
        // Convert to TWD
        profit = price - bought_price * 30/6.5;
         var symbol = 'NT$';
    }

    // Update the price field with the converted value
document.getElementById('profit-display').innerHTML = symbol + profit;}
</script>

</html>

web/taobaoside/templates/taobaoside/base.html
<!doctype html>
  {% load static i18n%}
{% get_current_language as LANGUAGE_CODE%}
<html lang="{{LANGUAGE_CODE}}">
<head>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- FAV ADD  -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'taobaoside/css/bootstrap.min.css'%}"> -->

  <!-- STYLE LINK  -->
  <script src="{% static 'javascript/jquery-3.4.1.js' %}"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'taobaoside/css/main.css'%}"> -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@42,600,0,0" />
  <title>{% block title %}FastLine{% endblock title %}</title>
</head>
<body class="bg_body">
  <header id="header" class="py-4 bg__white">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container px-0">
        <a class="navbar-brand" href="{% url 'taobaoside:home' %}">
          <img class="img-fluid" src="{% static 'taobaoside/images/logo_beta.png'%}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto ms-5 mb-2 mb-lg-0 align-items-lg-center align-items-end">

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'taobaoside:home' %}">
                Dashboard
              </a>
            </li>

          

          </ul>
          <!-- account id  -->
          <!-- Example single danger button -->


        </div>

      </div>
    </nav>
  </header>
  <section class="page__tittle text-center d-md-none">
    <h2 class="pages__tittle font__700 pb-5">{% block phone_title%}Dashboard{% endblock phone_title%}</h2>
  </section>




 <div id="page-container" >
    <div id="content-wrap" class ="container">
     {% block content %}{% endblock %}
      </div>
      </div>







         {% include 'taobaoside/footer.html'%}

         <div style="display:none">
  </div>
       </body>





     </html>

web/taobaoside/templates/taobaoside/footer.html
{% load static i18n%}
<footer class="bg__black pb-5">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-md-3 mb-5 mb-xl-0">
        <div class="logo_footer mb-5">
          <!-- <a class="navbar-brand" href="/accounts/signup">
            <img class="img-fluid" src="{% static 'cryptick/images/logo.webp'%}" alt="">
          </a> -->
        </div>
        <div class="content__footer" style="margin-top:-10% !important">
          <!-- <p class="text__gray font__13">
            {% trans 'Cryptick is a young Canadian startup that want to simplify the calculation of your cryptoassets gains and losses. Our mission is to enable users to calculate their taxes as quickly and as easily as possible.'%}
              </p> -->
        </div>
      </div>
      <div class="col-md-3 mb-5 mb-xl-0">
        <h3 class="text-white text-capitalize mb-5 font__25">{% trans 'Useful links'%}</h3>
        <div class="d-md-flex justify-content-between d-block">
          
        </div>
      </div>


    </div>
  </div>
  <hr class="bg__gray my-5">
  <div class="footer__owner text-center">
    <p class="text__gray">
      ® 2022 FastLine Inc., {% trans 'All rights reserved.'%}
    </p>
  </div>
</footer>

web/taobaoside/templates/taobaoside/home.html
<!-- search_page.html -->
<html>
  <head>
    <title>Search</title>
    <style>
      /* Add a cool background image to the page */
      body {
        display: flex;
        align-items: center;
        justify-content: center;
        background-image: url('cool-background.jpg');
        background-size: cover;
        height: 100vh;
      }


      /* Center the search bar and footer on the page */
      .content {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }

      /* Style the search bar */
      form {
        display: flex;
        align-items: center;
        padding: 1em;
        background-color: rgba(255, 255, 255, 0.8);
        border-radius: 4px;
      }

      input[type="text"] {
        flex: 1;
        padding: 0.5em;
        font-size: 1.2em;
      }

      button[type="submit"] {
        padding: 0.5em 1em;
        border: none;
        background-color: #333;
        color: white;
        font-size: 1em;
        cursor: pointer;
      }

      /* Style the footer */
      footer {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        padding: 1em;
        background-color: rgba(255, 255, 255, 0.8);
        text-align: center;
      }
      .logo {
        width: 100px;
        height: 100px;
        background-size: cover;
      }
      .taobao-logo {
        background-image: url('taobao-logo.png');
      }

      .shopee-logo {
        background-image: url('shopee-logo.png');
      }

      .arrow {
        width: 0;
        height: 0;
        border-style: solid;
        border-width: 50px 0 50px 70px;
        border-color: transparent transparent transparent #333;
        margin: 0 1em;
      }
    </style>
  </head>
  <body>
    <div class="content">
      <h1>Search a product on taobao</h1>
      <form action="{% url 'taobaoside:search_item' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Search..." name='search_query'>
        <button type="submit">Go</button>
      </form>

    </div>
    <footer>
      Copyright 2022 FastLine
    </footer>
  </body>
</html>

web/taobaoside/templates/taobaoside/item_details.html
<html>
  <head>
    <title>Product</title>
    <style>
      .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #4CAF50;
        color: white;
        text-decoration: none;
        border-radius: 4px;
      }
    </style>
  </head>
  <body>
    <h1>Product details</h1>
    <div style="display: flex;">
      <div style="width: 200px;">
        <img src="{{ details.images.0 }}" alt="{{ details.title }}" style="width: 200px;" />
      </div>
      <div>
        <h2>{{details.title}}</h2>

        <p>Price: {{ details.price }}</p>
        <p>Promo: {{ details.promotion_price }}</p>
        <a href="{% url 'taobaoside:add_shopee' details.num_iid %}" class="button">Add to Shopee</a>
      </div>
    </div>
    <div>
      <h3>Additional Images</h3>
      <div style="width: 1200px;">
        {% for image in details.images|slice:"1:" %}
          <img src="{{ image }}" alt="{{ details.title }} additional image" style="width:200px"/>
        {% endfor %}
      </div>

      <div style="width: 1200px;">

        {% for image in images %}
          <img src="{{ image }}" alt="{{ details.title }} additional image" style="width:300px"/>
        {% endfor %}
      </div>
    </div>
  </body>
</html>

web/taobaoside/templates/taobaoside/product_added.html
<p>The product was added to your shopee</p>

<a href='/'>Go back the the home page</a>

web/taobaoside/templates/taobaoside/product_search_result.html
<html>
  <head>
    <title>Search Result</title>
  </head>
  <body>
    <h1>Your search result</h1>
    <div style="width: 1200px;">
    {% for item in items %}
      <a href="{% url 'taobaoside:item_detail' item.num_iid %}" style="float: left; margin-right: 20px;width : 190px;">
        <img src="{{ item.pic }}" alt="{{ item.title }}" style="width : 190px"/>
        <p>{{ item.title }}</p>
        <p>Price: {{ item.price }}</p>
        <p>Promo: {{ item.promotion_price }}</p>
        <p>Seller: {{ item.shop_title }}</p>
      </a>
      {% if forloop.counter|divisibleby:5 %}
        <div style="clear: both;"></div>
      {% endif %}
    {% endfor %}
  </div>
  </body>
</html>